models/Order.php
<?php

namespace app\models;

use Yii;
use yii\db\Query;

/**
 * This is the model class for table "order".
 *
 * @property integer $id
 * @property string $date_create
 * @property string $date_update
 * @property string $datetime_booking
 * @property integer $status_id
 * @property integer $from_point_id
 * @property integer $to_point_id
 * @property string $text_table
 * @property integer $car_class_id
 * @property integer $car_id
 * @property integer $tariff_id
 * @property integer $passengers
 * @property integer $price
 * @property string $comment
 *
 * @property Status $status
 * @property Car $car
 * @property Client $client
 * @property Driver $driver
 * @property Point $fromPoint
 * @property Tariff $tariff
 * @property Point $toPoint
 */
class Order extends \yii\db\ActiveRecord
{

	public $address;
	public $time;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date_create', 'date_update', 'time', 'datetime_booking'], 'safe'],
            [['client_id', 'status_id', 'from_point_id', 'to_point_id', 'car_class_id', 'car_id', 'tariff_id', 'driver_id', 'price'], 'integer'],
	        [['passengers'], 'number', 'min' => 1, 'max' => 24],
            [['text_table'], 'string', 'max' => 256],
            [['comment'], 'string', 'max' => 1024],
	        [['driver_id'], 'exist', 'skipOnError' => true, 'targetClass' => Driver::className(), 'targetAttribute' => ['driver_id' => 'id']],
            [['status_id'], 'exist', 'skipOnError' => true, 'targetClass' => Status::className(), 'targetAttribute' => ['status_id' => 'id']],
            [['car_id'], 'exist', 'skipOnError' => true, 'targetClass' => Car::className(), 'targetAttribute' => ['car_id' => 'id']],
            [['from_point_id'], 'exist', 'skipOnError' => true, 'targetClass' => Point::className(), 'targetAttribute' => ['from_point_id' => 'id']],
            [['tariff_id'], 'exist', 'skipOnError' => true, 'targetClass' => Tariff::className(), 'targetAttribute' => ['tariff_id' => 'id']],
            [['to_point_id'], 'exist', 'skipOnError' => true, 'targetClass' => Point::className(), 'targetAttribute' => ['to_point_id' => 'id']],
	        [['status_id', 'from_point_id', 'to_point_id', 'tariff_id', 'passengers'], 'required'],
	        [['time', 'datetime_booking'], 'required', 'on' => 'hire'],
	        [['driver_id', 'car_id'], 'required', 'on' => 'purpose']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'date_create' => Yii::t('app', 'Date Create'),
            'date_update' => Yii::t('app', 'Date Update'),
            'datetime_booking' => Yii::t('app', 'Дата заказа'),
            'status_id' => Yii::t('app', 'Status'),
            'from_point_id' => Yii::t('app', 'Пункт'),
            'to_point_id' => Yii::t('app', 'Пункт'),
            'text_table' => Yii::t('app', 'Text Table'),
            'car_class_id' => Yii::t('app', 'Car Class ID'),
            'car_id' => Yii::t('app', 'Car'),
            'driver_id' => Yii::t('app', 'Driver'),
            'tariff_id' => Yii::t('app', 'Tariff'),
            'passengers' => Yii::t('app', 'Passengers'),
            'comment' => Yii::t('app', 'Комментарий'),
	        'client_id' => Yii::t('app', 'Client'),
	        'time' => Yii::t('app', 'Время'),
	        'price' => Yii::t('app', 'Сумма')
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(Status::className(), ['id' => 'status_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCar()
    {
        return $this->hasOne(Car::className(), ['id' => 'car_id']);
    }

	public function getDriver()
	{
		return $this->hasOne(Driver::className(), ['id' => 'driver_id']);
	}

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFromPoint()
    {
        return $this->hasOne(Point::className(), ['id' => 'from_point_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTariff()
    {
        return $this->hasOne(Tariff::className(), ['id' => 'tariff_id']);
    }

	public function getClient()
	{
		return $this->hasOne(User::className(), ['id' => 'client_id']);
	}

	public function getUser()
	{
		return $this->hasOne(User::className(), ['id' => 'client_id']);
	}

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getToPoint()
    {
        return $this->hasOne(Point::className(), ['id' => 'to_point_id']);
    }

	public function getPrice()
	{
		return Transfer::getPrice($this->from_point_id, $this->to_point_id, $this->tariff_id);
	}

	public function loadAddress()
	{
		if ($this->isNewRecord)
		{
			$this->address = new Address();
		}
		else
		{
			$this->address = Address::findOne(['order_id' => $this->id]);
		}
	}

	public function afterSave($insert, $changedAttributes)
	{
		if ($this->address)
		{
			$this->address->order_id = $this->id;
			$this->address->save();
		}
	}

	public function sendSmsToDriver()
	{
		$soapClient = new \SoapClient('http://smsc.ru/sys/soap.php?wsdl');
		$message = 'Номер заказа: '.$this->id.'. '.'Время: '.date('H:i d.m.Y', strtotime($this->datetime_booking)).'. '
		.'Откуда: '.$this->fromPoint->getPoint().' ';
//		$this->fromPoint->address ?	$message .= $this->fromPoint->address.' ' : null;
		$this->address->from_street ? $message .= $this->address->from_street.' ' : null;
		$this->address->from_home ? $message .= $this->address->from_home.' ' : null;
		$message .= '. Куда: '.$this->toPoint->getPoint().' ';
//		$this->toPoint->address ? $message .= $this->toPoint->address.' ' : null;
		$this->address->to_street ? $message .= $this->address->to_street.' ' : null;
		$this->address->to_home ? $message .= $this->address->to_home.' ' : null;
		if ($this->price)
		{
			$message .= '. Цена: ';
			$message .= $this->price;
		}
		$message .= '. Пассажиры: ';
		$message .= $this->passengers.'';

		$this->comment ? $message .= ' Комментарий: '.$this->comment : null;

		$result = $soapClient->send_sms([
			'login' => 'transfer-ufa',
			'psw' => 'e127cp102',
			'phones' => $this->driver->phone_number,
			'mes' => $message,
			'id' => $this->id,
			'sender' => 'TRANSFERUFA'
		]);

		$error = $result->sendresult->error;

		if (isset($result->sendresult->error))
			return $this->getErrorText($result->sendresult->error);
		else
			return true;
	}

	public function getErrorText($id)
	{
		$errorMsg = [
			1	=>  "Ошибка в параметрах.",
			2	=>  "Неверный логин или пароль.",
			3	=>  "Недостаточно средств на счету Клиента.",
			4	=>  "IP-адрес временно заблокирован из-за частых ошибок в запросах. Подробнее",
			5	=>  "Неверный формат даты.",
			6	=>  "Сообщение запрещено (по тексту или по имени отправителя).",
			7	=>  "Неверный формат номера телефона.",
			8	=>  "Сообщение на указанный номер не может быть доставлено.",
			9	=>  "Отправка более одного одинакового запроса на передачу SMS-сообщения в течение минуты."
		];
		return $errorMsg[$id];
	}

	public function sendEmail()
	{
		$result = Yii::$app->mailer->compose('order', [
			'order' => $this
		])
			->setTo($this->client->email)
			->setFrom('no-reply@renova-ufa.ru')
			->setSubject('Заказ')
			->send();
		if ($result)
			return true;
	}
}

controllers/OrderController.php
<?php

namespace app\controllers;

use dektrium\user\filters\AccessRule;
use app\models\User;
use Yii;
use app\models\Order;
use app\models\OrderSearch;
use yii\base\Response;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
    /**
     * @inheritdoc
     */
	public function behaviors()
	{
		return [
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete'  => ['post'],
					'confirm' => ['post'],
					'block'   => ['post'],
				],
			],
			'access' => [
				'class' => AccessControl::className(),
				'ruleConfig' => [
					'class' => AccessRule::className(),
				],
				'rules' => [
					[
						'allow' => true,
						'roles' => ['@'],
						'actions' => [
							'index',
							'create',
							'update'
						],
						'matchCallback' => function(){
							return in_array(Yii::$app->user->identity->role_id, [
								User::ROLE_ADMIN,
								User::ROLE_MANAGER,
								User::ROLE_ACCOUNTANT,
								User::LEGAL_ENTITY,
								User::INDIVIDUAL,
							]);
						}
					],
					[
						'allow' => true,
						'roles' => ['@'],
						'matchCallback' => function(){
							return Yii::$app->user->identity->role_id == User::ROLE_ADMIN;
						}
					],
				],
			]
		];
	}

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrderSearch();
		$user = Yii::$app->user->identity;
	    if (Yii::$app->request->isAjax)
	    {
		    $post = ['Order' => $_POST];
		    $order = Order::findOne($_POST['id']);
		    if ($order->load($post))
		    {
			    $order->save();
		    }
		    return true;
	    }
	    if (Yii::$app->user->identity->role_id == 6 || Yii::$app->user->identity->role_id == 2)
	    {
		    $searchModel->client_id = Yii::$app->user->id;
		    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		    return $this->render('user_index', [
			    'searchModel' => $searchModel,
			    'dataProvider' => $dataProvider,
		    ]);
	    }
	    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Order model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Order();
	    $model->loadAddress();
	    $model->scenario = 'hire';
        if ($model->load(Yii::$app->request->post()) && $model->address->load(Yii::$app->request->post())) {
	        $datetime = date('Y-m-d H:i:s', strtotime("$model->datetime_booking $model->time"));
	        $model->datetime_booking = $datetime;
	        $model->status_id = 1;
	        $model->client_id = Yii::$app->user->identity->getId();
	        if (Yii::$app->user->identity->role_id == User::LEGAL_ENTITY || Yii::$app->user->identity->role_id == User::INDIVIDUAL) {
		        if ($model->getPrice()) $model->price = $model->getPrice();
	        }
	        if ($model->save())
	        {
		        return $this->redirect(['order/index']);
	        }
        } else {
	        !$model->datetime_booking ? $model->datetime_booking = date('d.m.Y', time()+1800) : null;
	        !$model->time ? $model->time = date('H:i', time()+1800) : null;
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
	    $model->fromPoint;
	    $model->toPoint;
	    if (Yii::$app->user->identity->role_id == User::ROLE_ADMIN || Yii::$app->user->identity->role_id == User::ROLE_MANAGER)
	    {
		    $model->scenario = 'purpose';
		    if (!$model->price)
		    {
			    if ($model->getPrice()) $model->price = $model->getPrice();
		    }
	    }
	    if (Yii::$app->user->identity->role_id == User::LEGAL_ENTITY || Yii::$app->user->identity->role_id == User::INDIVIDUAL)
	    {
		    if ($model->getPrice()) $model->price = $model->getPrice();
		    if ($model->status_id != 1)
			    $this->redirect(['order/index']);
	    }
	    $model->loadAddress();



        if ($model->load(Yii::$app->request->post()) && $model->address->load(Yii::$app->request->post())) {
	        $datetime = date('Y-m-d H:i:s', strtotime("$model->datetime_booking $model->time"));
	        $model->datetime_booking = $datetime;
	        if ($model->save())
	        {
		        $model->sendSmsToDriver();
		        return $this->redirect(['order/index']);
	        }
        } else {
	        $model->time = date('H:i', strtotime($model->datetime_booking));
	        $model->datetime_booking = date('d.m.Y', strtotime($model->datetime_booking));
	        return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

	/**
	 * @param $id
	 * @return bool
	 */

	public function actionSendSms($id)
	{
		if (Yii::$app->request->isAjax)
		{
			$order = Order::findOne($id);
			Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
			return $order->sendSmsToDriver();
		}
	}

	/**
	 * @param $id
	 * @return bool
	 */

	public function actionSendEmail($id)
	{
		if (Yii::$app->request->isAjax)
		{
			$order = Order::findOne($id);
			Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
			if ($order->sendEmail())
				return true;
			else
				return false;
		}
	}

    /**
     * Deletes an existing Order model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/order/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\OrderSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'date_create') ?>

    <?= $form->field($model, 'date_update') ?>

    <?= $form->field($model, 'datetime_booking') ?>

    <?= $form->field($model, 'status_id') ?>

    <?php // echo $form->field($model, 'from_point_id') ?>

    <?php // echo $form->field($model, 'to_point_id') ?>

    <?php // echo $form->field($model, 'text_table') ?>

    <?php // echo $form->field($model, 'car_class_id') ?>

    <?php // echo $form->field($model, 'car_id') ?>

    <?php // echo $form->field($model, 'tariff_id') ?>

    <?php // echo $form->field($model, 'passengers') ?>

    <?php // echo $form->field($model, 'comment') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/order/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Order */

$this->title = Yii::t('app', 'Create Order');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Orders'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?

    if (Yii::$app->user->identity->role_id == 2 || Yii::$app->user->identity->role_id == 5)
    {
	    echo $this->render('_user_form', [
		    'model' => $model,
	    ]);
	}
    else
        echo $this->render('_admin_form', [
	    'model' => $model,
    ]);
    ?>

</div>

views/order/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
//use kartik\grid\GridView;
//use kartik\editable\Editable;
/* @var $this yii\web\View */
/* @var $searchModel app\models\OrderSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$css = <<< CSS
thead select {
    width: 80px;
}
.form-control {
	   width: 100%;
    height: 25px;
    padding: 0;
}
tr > th {
	padding:0px !important;
}
CSS;
$urlGetCars = \yii\helpers\Url::to('/driver/get-drop-down');
$urlSendSms = \yii\helpers\Url::to('/order/send-sms');
$urlSendEmail = \yii\helpers\Url::to('/order/send-email');
$ajaxUrl = \yii\helpers\Url::to('/order/index');
$js = <<< JS
$('select').addClass('form-control');
function replaceCarsDropDown(item_id)
{
	$.ajax({
		url : '$urlGetCars',
		type : 'post',
		data : {
			id : $('select[name="driver_id"][item_id="'+item_id+'"]').val(),
			order_id: item_id
		},
		success : function(data){
			$('select[name="car_id"][item_id="'+item_id+'"]').empty();
			$('select[name="car_id"][item_id="'+item_id+'"]').append(data);
		}
	})
}
$('tbody select').on('input', function(){
	var item_id = $(this).attr('item_id');
	var status_id = $('select[name="status_id"][item_id="'+item_id+'"]').val();
	var car_id = $('select[name="car_id"][item_id="'+item_id+'"]').val();
	if ($(this).attr('name') == 'driver_id') replaceCarsDropDown(item_id);
	var driver_id = $('select[name="driver_id"][item_id="'+item_id+'"]').val();
	console.log(status);
	$.ajax({
		url : '$ajaxUrl',
		type: 'post',
		data : {
			id : item_id,
			status_id : status_id,
			car_id : car_id,
			driver_id : driver_id,
		}
	});
});
$('.send_sms').click(function(){
	var order_id = $(this).attr('order_id');
	$(item).removeClass('button-success');
	$(item).removeClass('button-fail');
	$(this).addClass('button-click');
	$(item).next().next().addClass('hidden');
	$(item).next().next().removeClass('button-success');
	$(item).next().next().removeClass('button-fail');
	var item = this;
	$.ajax({
		url: '$urlSendSms'+'?id='+order_id,
		type: 'get',
		success: function(data){
			console.log(data);
			if (data == true)
			{
				$(item).next().next().addClass('button-success');
				$(item).next().next().removeClass('hidden');
				$(item).next().next().html("Отправлено");
				$(item).removeClass('button-click');
				$(item).addClass('button-success');
			}
			else
			{
				$(item).next().next().addClass('button-fail');
				$(item).next().next().removeClass('hidden');
				$(item).next().next().html(data);
				$(item).removeClass('button-click');
				$(item).addClass('button-fail');
			}

		}
	}).fail(function(){
		$(this).removeClass('button-click');
		$(this).addClass('button-fail');
	});
});
$('.send_email').click(function(){
	var order_id = $(this).attr('order_id');
	$(item).removeClass('button-success');
	$(item).removeClass('button-fail');
	$(this).addClass('button-click');
	$(item).next().next().addClass('hidden');
	$(item).next().next().removeClass('button-success');
	$(item).next().next().removeClass('button-fail');
	var item = this;
	$.ajax({
		url: '$urlSendEmail'+'?id='+order_id,
		type: 'get',
		success: function(data){
			console.log(data);
			if (data == true)
			{
				$(item).next().next().addClass('button-success');
				$(item).next().next().removeClass('hidden');
				$(item).next().next().html("Отправлено");
				$(item).removeClass('button-click');
				$(item).addClass('button-success');
			}
			else
			{
				$(item).next().next().addClass('button-fail');
				$(item).next().next().removeClass('hidden');
				$(item).next().next().html(data);
				$(item).removeClass('button-click');
				$(item).addClass('button-fail');
			}

		}
	}).fail(function(){
		$(this).removeClass('button-click');
		$(this).addClass('button-fail');
	});
})
JS;
$jsBody = <<< JS
$('body').addClass('sidebar-collapse');
JS;


$this->registerCss($css);
$this->registerJs($js);
$this->registerJs($jsBody, \yii\web\View::POS_END);
$this->title = Yii::t('app', 'Orders');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Order'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
//            ['class' => 'yii\grid\SerialColumn'],

            'id',
	        [
		        'attribute' => 'datetime_booking',
		        'format' => 'raw',
		        'value' => function($model){
			        return date('d.m.Y', strtotime($model->datetime_booking)).'<br>'.date('H:i', strtotime($model->datetime_booking));
		        },
		        'contentOptions' => [
			        'style' => 'width: 10%;'
		        ]
	        ],
	        [
		        'attribute' => 'from_point_id',
		        'label' => 'Откуда',
		        'value' => function($model)
		        {
			        return \app\models\Transfer::getPointById($model->from_point_id);
		        },
		        'filter' => Html::activeDropDownList(
			        $searchModel,
			        'from_point_id',
			        \app\models\Transfer::getPointsForDropDownList(),
			        [
				        'prompt' => Yii::t('app', 'Choose')
			        ]),
		        'contentOptions' => [
			        'style' => 'max-width: 15%;width: 10%;'
		        ]
	        ],
	        [
		        'attribute' => 'to_point_id',
		        'label' => 'Куда',
		        'value' => function($model)
		        {
			        return \app\models\Transfer::getPointById($model->to_point_id);
		        },
		        'filter' => Html::activeDropDownList(
			        $searchModel,
			        'to_point_id',
			        \app\models\Transfer::getPointsForDropDownList(),
			        [
				        'prompt' => Yii::t('app', 'Choose')
			        ]),
		        'contentOptions' => [
			        'style' => 'max-width: 15%;width: 10%;'
		        ]
	        ],
	        [
		        'attribute' => 'client_id',
		        'format' => 'raw',
		        'value' => function($model)
		        {
			        $arr = \app\models\Client::getUserInfo($model->client_id);
			        $echo = $arr['title'];
			        return Html::a($echo, \yii\helpers\Url::toRoute(['client/update', 'id' => $model->client_id]));
		        },
		        'filter' => Html::activeDropDownList(
			        $searchModel,
			        'client_id',
			        \app\models\Client::getClientsForDropDownList(),
			        [
				        'prompt' => Yii::t('app', 'Choose')
			        ]),
		        'contentOptions' => [
			        'style' => 'max-width: 15%;width: 5%;'
		        ]
	        ],
	        [
		        'attribute' => 'car_id',
		        'format' => 'raw',
		        'label' => 'Обслуживание',
		        'value' => function($model) {
			        return
				        Html::tag('div', '<b>Класс: </b>'.$model->getTariff()->one()['name']).
			            Html::tag('div', '<b>Пассажиры: </b>'.$model->passengers).
			            Html::tag('div', '<b>Комментарий: </b>'.$model->comment);
		        },
		        'contentOptions'=> [
			        'style'=>'width:15%'
		        ],
		        'filter' => false
	        ],

	        [
		        'attribute' => 'price',
		        'contentOptions'=> [
			        'style'=>'width:5%'
		        ],
                'value' => function($model) {
	                $return = $model->price ? $model->price.'р.' : null;
	                return $return;
                }
//		        'label' => 'Стоимость',
	        ],
	        [
		        'attribute' => 'driver_id',
		        'label' => 'Водитель, авто',
		        'format' => 'raw',
		        'value' => function($model){
			        $driver = \app\models\Driver::findOne($model->driver_id);
			        return
			            '<strong>Водитель: </strong>'.Html::dropDownList('driver_id', $model->driver_id, \app\models\Driver::getDriversForDropdownList(), [
				            'item_id' => $model->id,
				            'prompt' => '--'
			            ]).
				        Html::tag('br', '', ['style' => 'margin:5px']).
			            '<strong>Автомобиль: </strong>'.Html::dropDownList('car_id', $model->car_id, \app\models\Car::getCarsForDropDownList(), [
				            'item_id' => $model->id,
				            'prompt' => '--'
			            ]).
			            Html::tag('div', '<strong>Номер: </strong>'.($driver['phone_number'] ? $driver['phone_number'] : $driver['phone_number_2']));
		        },
		        'filter' => Html::activeDropDownList(
			        $searchModel,
			        'driver_id',
			        \app\models\Driver::getDriversForDropdownList(),
			        [
				        'prompt' => Yii::t('app', 'Choose')
			        ]),
		        'contentOptions'=> [
			        'style'=>'width:15%'
		        ],
	        ],
	        [
		        'attribute' => 'status_id',
		        'format' => 'raw',
		        'value' => function($model){
			        return
				        Html::dropDownList('status_id', $model->status_id, \app\models\Status::getStatusListForDropDownList(), [
				        'item_id' => $model->id
			        ])
				        .'<br>'.Html::button('Отправить смс', [
				        'order_id' => $model->id,
				        'class' => 'send_sms'
				        ])
				        .'<br><div class="hidden"></div>'
				        .'<br>'.Html::button('Отправить email', [
				        'order_id' => $model->id,
				        'class' => 'send_email'
			        ]).'<br><div class="hidden"></div>';
		        },
		        'filter' => Html::activeDropDownList(
			        $searchModel,
			        'status_id',
			        \app\models\Status::getStatusListForDropDownList(),
			        [
				        'prompt' => Yii::t('app', 'Choose')
			        ]),
		        'contentOptions'=> [
			        'style'=>'width:12%'
		        ],
	        ],
            [
	            'class' => 'yii\grid\ActionColumn',
	            'template' => '{update} {delete}',
            ],
        ],
    ]); ?>
</div>